# This is a basic workflow to help you get started with Actions

name: Build Artifact

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-maven:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-18.04 ]
        java: [ 11, 15, 16 ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up java 15
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }} # The JDK version to make available on the path.

      # Builds and installs the artifact
      - name: Build and Install
        run: ./mvnw clean install

  # This workflow contains a single job called "build"
  build-gradle:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-18.04 ]
        java: [ 11, 15 ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Sets up java 15
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }} # The JDK version to make available on the path.

      # Builds and installs the artifact
      - name: Build and Install
        run: ./gradlew clean build
